services:
  # https://caddyserver.com/docs/running#setup
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    environment:
      - DOMAIN=$DOMAIN
      - CERT_EMAIL=$CERT_EMAIL
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - 80:80
      - 443:443

  node-server-1:
    build:
      context: .
      dockerfile: Dockerfile.nodeserver
    restart: unless-stopped
    container_name: node-server-1
    environment:
      - PORT=5000

  node-server-2:
    build:
      context: .
      dockerfile: Dockerfile.nodeserver
    restart: unless-stopped
    container_name: node-server-2
    environment:
      - PORT=5000
