services:
  # https://caddyserver.com/docs/running#setup
  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN:-http://localhost:80}
      - CERT_EMAIL=$CERT_EMAIL
      - UPSTREAMS=go-server-1:5000 go-server-2:5000
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - 80:80
      - 443:443

  go-server-1:
    build:
      context: .
      dockerfile: Dockerfile.goserver
    restart: unless-stopped
    container_name: go-server-1
    environment:
      - PORT=5000

  go-server-2:
    build:
      context: .
      dockerfile: Dockerfile.goserver
    restart: unless-stopped
    container_name: go-server-1
    environment:
      - PORT=5000
