name: publish-image

on:
  push:
    tags:
      - "*"

env:
  # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
  # github.repository as <username>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/docker/login-action?tab=readme-ov-file#github-container-registry
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build Image"
        run: |
          docker build -t ghcr.io/{{ env.IMAGE_NAME }}:latest .
          docker push ghcr.io/{{ env.IMAGE_NAME }}:latest
